site_name: Portafolio Swift
use_directory_urls: false

plugins:
    - search
    - localsearch

theme:
  icon:
    admonition:
      note: octicons/beaker-16
  font: false
  name: material
  language: es
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  custom_dir: theme

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav: 
  - Introduccion: index.md
  - Unidad 1:
    - Clases: contenido/unidad_1/clases.md
    - Ejercicios del libro: contenido/unidad_1/libro.md


